---
- name: Install mysql-nginx-phpfpm
  hosts: all

  tasks:
  - name: Add repo NGINX
    template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
  - name: Install NGINX
    shell: " yum -y update && \
             yum -y install nginx && \
             systemctl start nginx "
  - name: Install PHP-FPM
    shell: " yum -y install epel-release && \
             yum -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
             yum -y install yum-utils && \
             yum-config-manager --enable remi-php72 && \
             yum -y update && \
             yum -y install php && \
             yum -y install php-fpm php-gd php-json php-mbstring php-mysqlnd php-xml php-xmlrpc php-opcache && \
             systemctl start php-fpm "
  - name: Install MySQL
    shell: " yum -y localinstall https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm && \
             yum -y update && \
             yum -y install mysql-community-server && \
             service mysqld start "
  - name: Get default password mysql
    shell: " grep 'temporary password' /var/log/mysqld.log | awk '{print($11)}' "
    register: password
    ignore_errors: True
  - name: Retrieve stuff from mysql
    command: >
       mysql -uroot -p{{ password.stdout }} --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Vega123312##';"
    check_mode: no
    changed_when: False
  - name: Tunning Mysql
    template: src=my.cnf dest=/etc/my.cnf
  - name: Tunning system
    template: src=sysctl.conf dest=/etc/sysctl.conf
  - name: Restart mysql
    shell: "service mysqld restart"
